### ISSUE TITLE
🛬 [INBOUND] - django-tailwind-cli

### ISSUE THREAD

**Issue by oliverandrich** [django-commons/membership#67]
### What's the URL to the project?

https://github.com/oliverandrich/django-tailwind-cli

### Who are the current maintainers?

@oliverandrich

### Does the project have the required attributes?

- [X] Does the project have tests?
- [X] Does the project have documentation?
- [X] Has the project adopted [Django Commons's Code of Conduct](https://github.com/django-commons/membership/blob/main/CODE_OF_CONDUCT.md)?

### Who will be the new maintainers of the project?

@oliverandrich

**Comment by ryancheley** [comment]
I agree with @tim-schilling. This looks like a great project to bring on board and has a lot of usage in the Django Community based on the [dependents](https://github.com/oliverandrich/django-tailwind-cli/network/dependents) I’m seeing.

**Comment by oliverandrich** [comment]
One hope I have is that the move to django-commons might lead to finding another co-maintainer or motivate someone to come forward.

**Comment by joshuadavidthomas** [comment]
+1 from me as well. 

@tim-schilling Is there something formally written down about what would constitute a personal project? I would think one purpose of Django Commons is to take on these types of projects that have gotten popular in the community but are currently hosted on the maintainer's personal GitHub profile. Is there a defined line where the answer would be "No thanks"? Or is it up to consensus amongst the members?

**Comment by tim-schilling** [comment]
@oliverandrich yeah, that makes a lot of sense.

@joshuadavidthomas I don't believe we have a defined policy yet. That'd be a good discussion topic if you don't mind creating it and tagging the admins on it so we get alerted.

**Comment by oliverandrich** [comment]
Where do we stand with this ticket? What would be the next steps?

**Comment by tim-schilling** [comment]
@ryancheley is going to schedule time with you to do the transfer. If you want to send some available times that may help the process along. Otherwise I suspect he'll use a meeting poll tool.

@oliverandrich we also added some new questions to the issue form that predated your request. Could you answer the following? These are entirely up to you and can be changed at a later time.

1. Does the project have a test.pypi.org project?
2. Would you like to test your deployments with uploads to test.pypi.org (you'll need to create the project first)?
3. Would you like to use GitHub's merge commits?
4. Would you like to use GitHub's rebase and merge?
5. Would you like to use GitHub's squash and merge?
6. Would you like to use GitHub's Discussions?
7. Would you like to use GitHub's Wiki?

**Comment by ryancheley** [comment]
@oliverandrich here's a link to times that I'm available over the next 2 weeks

https://calendly.com/rcheley/django-commons-inbound-setup?month=2024-10
https://calendly.com/rcheley/django-commons-inbound-setup?month=2024-11

The process is typically taking about 75 minutes (@cunla or @tim-schilling correct me if I'm wrong on that!)

If you can select 2 times that will help with making sure other admins are able to attend as well.

**Comment by tim-schilling** [comment]
Yeah, that's roughly how long it's taken for the two I was a part of.

**Comment by Stormheg** [comment]
Closing as we moved this in yesterday 🥳 

https://github.com/django-commons/django-tailwind-cli
